// Code generated by MockGen. DO NOT EDIT.
// Source: services/list.go
//
// Generated by this command:
//
//	mockgen -source=services/list.go -destination=services/mocks/mock_list_service.go -package=mocks ListService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dtos "sirichai-bank/dtos"
	reflect "reflect"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	gomock "go.uber.org/mock/gomock"
)

// MockListService is a mock of ListService interface.
type MockListService struct {
	ctrl     *gomock.Controller
	recorder *MockListServiceMockRecorder
}

// MockListServiceMockRecorder is the mock recorder for MockListService.
type MockListServiceMockRecorder struct {
	mock *MockListService
}

// NewMockListService creates a new mock instance.
func NewMockListService(ctrl *gomock.Controller) *MockListService {
	mock := &MockListService{ctrl: ctrl}
	mock.recorder = &MockListServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListService) EXPECT() *MockListServiceMockRecorder {
	return m.recorder
}

// DeleteOne mocks base method.
func (m *MockListService) DeleteOne(ctx context.Context, filter primitive.D) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOne", ctx, filter)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOne indicates an expected call of DeleteOne.
func (mr *MockListServiceMockRecorder) DeleteOne(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*MockListService)(nil).DeleteOne), ctx, filter)
}

// FindAll mocks base method.
func (m *MockListService) FindAll(ctx context.Context, filter ...primitive.E) ([]dtos.Listing, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range filter {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindAll", varargs...)
	ret0, _ := ret[0].([]dtos.Listing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockListServiceMockRecorder) FindAll(ctx any, filter ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, filter...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockListService)(nil).FindAll), varargs...)
}

// FindByKeyValue mocks base method.
func (m *MockListService) FindByKeyValue(ctx context.Context, key string, value any, opts ...primitive.E) ([]dtos.Listing, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, value}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindByKeyValue", varargs...)
	ret0, _ := ret[0].([]dtos.Listing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKeyValue indicates an expected call of FindByKeyValue.
func (mr *MockListServiceMockRecorder) FindByKeyValue(ctx, key, value any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, value}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKeyValue", reflect.TypeOf((*MockListService)(nil).FindByKeyValue), varargs...)
}

// FindOneAndUpdate mocks base method.
func (m *MockListService) FindOneAndUpdate(ctx context.Context, filter, update primitive.D) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneAndUpdate", ctx, filter, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindOneAndUpdate indicates an expected call of FindOneAndUpdate.
func (mr *MockListServiceMockRecorder) FindOneAndUpdate(ctx, filter, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneAndUpdate", reflect.TypeOf((*MockListService)(nil).FindOneAndUpdate), ctx, filter, update)
}

// FindOneKeyValue mocks base method.
func (m *MockListService) FindOneKeyValue(ctx context.Context, key string, value any, opts ...primitive.E) (*dtos.Listing, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, value}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOneKeyValue", varargs...)
	ret0, _ := ret[0].(*dtos.Listing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneKeyValue indicates an expected call of FindOneKeyValue.
func (mr *MockListServiceMockRecorder) FindOneKeyValue(ctx, key, value any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, value}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneKeyValue", reflect.TypeOf((*MockListService)(nil).FindOneKeyValue), varargs...)
}

// InsertOne mocks base method.
func (m *MockListService) InsertOne(ctx context.Context, t dtos.Listing) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOne", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOne indicates an expected call of InsertOne.
func (mr *MockListServiceMockRecorder) InsertOne(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockListService)(nil).InsertOne), ctx, t)
}
