service:
  port: 8080

database:
  firebase:
    credentials: "./cmd/conf/credentials/firebase_credentials.json"

  mongo:
    url: "mongodb://localhost:27017"
    db_name: "daveslist"
    db_username: root
    db_password: P@ssw0rd
    admin_db_email: "admin@mail.com"
    admin_db_password: "P@ssw0rd"

auth:
  secret: "sirichai-44-secret-key"

